### ISSUE TITLE
Contact Diagrams folks?

### ISSUE THREAD

**Issue by srush** [chalk-diagrams/chalk#117]
This isn't an issue, but I saw that there is a diagram mailing list https://groups.google.com/g/diagrams-discuss and that they seem to be active on a v2.0. Thought it might be fun to reach out and say hi. What do you think?

**Comment by danoneata** [comment]
Hey!

Yes, I definitely agree that it would be nice on our side to say "thank you" and acknowledge their very impressive work, given how much inspiration we drew from their library 🙂 Feel free to tag me as well, if you have time to compose a message for them.

I was aware of their mailing list. In fact, in #113 you mentioned that it would be nice to attach labels to arrows, so I looking in there for some pointers and found some potential ideas [[1](https://groups.google.com/g/diagrams-discuss/c/luTLm0E2flU/m/eC8eP_XHFQAJ), [2](https://groups.google.com/g/diagrams-discuss/c/Iynd_IdL2CY/m/r1uT-VCMBQAJ)].
 
I also wanted to apologize for being slow with the development of the PR #116; I had a busier week than usual, but I hope to  resume work over the weekend.

Thanks!

**Comment by srush** [comment]
Don't worry at all! I'm looking forward to the change, but this is all just for fun.
