### ISSUE TITLE
SVGs getting very large

### ISSUE THREAD

**Issue by jerinphilip** [chalk-diagrams/chalk#123]
I'm trying to replicate some of the diagrams in [Understanding LSTM Networks](https://colah.github.io/posts/2015-08-Understanding-LSTMs/) with some variations using _chalk_, mostly for trying out (nothing serious, really).

The following is an attempted render in progress of an SSRU[1], in a similar style, using _chalk_:

<img src="https://github.com/chalk-diagrams/chalk/assets/727292/5d1ce396-1b8e-425a-a2aa-354297cdf2e9" width=600px>

This one uses LaTeX, as you can see from the picture and is very slow to write-out. I suspect this is due to several spawns of diagram generation commands involving LaTex. I also suspect there's some stitching together of glyphs from the latex fonts over subdiagrams happening which is leading to the large size (75MB). One more thing I notice is a large number `<g>.. </g>` in the SVG code. This is also making it difficult to do some finishing touches in _inkscape_.  

Code is not in a great shape, but please find it [here](https://gist.github.com/jerinphilip/098817ffbe9d01b2ae51c051fb35ccb1). 

[1] [From Research to Production and Back: Ludicrously Fast Neural Machine Translation](https://aclanthology.org/D19-5632.pdf)

**Comment by srush** [comment]
This is such a cool project. Thanks for trying out Chalk!
